config/routes.rb
HelloWorld::Application.routes.draw do
  resources :programs


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/program.rb
class Program < ActiveRecord::Base
  # attr_accessible :title, :body
  has_and_belongs_to_many :users
  attr_accessible :name, :intro, :description

  def to_param
    name
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  after_create :send_welcome_mail
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :programs

  def send_welcome_mail
    UserNotifier.welcome_mail(id).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @programs = Program.all
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find_by_name(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find_by_name(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find_by_name(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find_by_name(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <li class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </li>
  <% end %>
  <li class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </li>
  <% if ContactUs.require_subject %>
    <li class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </li>
  <% end %>
  <li class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </li>
  <li class='commit'>
    <%= f.submit :submit, :alt => t('.submit'), :class => 'submit create', :label => t('.submit'), :title => t('.submit') %>
  </li>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<div class='raw'>
  <div class='span6'>
  <a href="https://twitter.com/HelloWorldKE" class="twitter-follow-button" data-show-count="false">Follow @HelloWorldKE</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <h1>Email Us!</h1>
    <%= simple_form_for @contact, :url => contacts_path do |f| %>
      <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
      <%= f.input :email, :label => t('.email') %>
      <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
      <%= f.input :message, :as => :text, :input_html => { :cols => 50, :rows => 8 }, :label => t('.message') %>
      <%= f.button :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit' } %>
    <% end %>
  </div>
  <div class="span5 pull-right">
    <div class='tweet'>
      <a class="twitter-timeline" href="https://twitter.com/NjeriChelimo" data-widget-id="342623886468325376">Tweets by @NjeriChelimo</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>

    <h1>Call Us!</h1></br>
    <h2 class='phone-number'>0722838469</h3>
  </div>
</div>

app/views/home/index.html.haml
%div.row
  %div.span7
    %a.span2{ :href => 'mailto:help@helloworld.co.ke?Subject=I%20want%20to%20Join%20helloWolrd!', :class => 'btn btn-primary btn-large'} Join HelloWorld!
    %span.span2
      = render :partial => 'tweet.html'
    %div.span2.fblike
      = render :partial => 'like.html'
    %div.hello-world
      %h1.why The New Geek on the block!
      %p
        HelloWorld is a  community of young learners, prospective entrepreneurs and  creatives using modern technology to build their careers and companies. We believe that tech, cool ideas, creativity, a supportive community, pizza and more entrepreneurs will make the world a better place!
      %p
        We CREATE. We don't admire beautiful design, we create beatiful design. We don't just use apps like Twitter, we build apps like Twitter. We are not just living life, we are shaping our paths.
      %p
        We embrace all your ideas ambitions and run with you towards your goals!
    %div.hello-world
      %h1.why What's our secret?
      %p
        We do all this through self learning and practical team projects. We enjoy self learning and believe it's the purest and most effective form of learning because it allows you to master what you are learning. You learn your subject of choice and at your pace of choice.
      %p
        We love to get our hands dirty in projects, from film and photography contests to hackathons, and we do this in teams! Team projects are fun, and effective. Some of the projects include: Building a company from company registration to making a sale you product or service, making a movie as a team, designing your personal brand, and much more!
    %div.hello-world
      %h1
        Sounds like your kind of thing?
      %p
        Techies are known not to be social, but we the exact opposite! We are a community. Do you enjoy learning new things? Do you like exercising you creativity? Do you love communities? Want to start your own successful company when you're young? Then you're ou kind of person! Join HelloWorld today!
    %div.hello-world.join-now
      %a{ :href => 'mailto:help@helloworld.co.ke?Subject=I%20want%20to%20Join%20helloWolrd!', :class => 'btn btn-primary btn-large join-btn'} Join HelloWorld!
  %div.span4.programs-intro
    %h1 Our Programs
    - @programs.each do |program|
      %div.programs
        %h2.program-title
          #{link_to program.name, program}
        %p
          = program.intro
        %p
          = link_to "Read more...", program
        %br

%script
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "HelloWorld", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to "Programs", programs_path
  %li
    = link_to "Contact Us", new_contact_path
%ul.nav.pull-right
  %li
    %a{ :href => 'mailto:help@helloworld.co.ke?Subject=I%20want%20to%20Join%20helloWolrd!', :class => ''} Join HelloWorld

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Helloworld"
      %meta{:content => content_for?(:description) ? yield(:description) : "helloWorld", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-inverse.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      %div.stripes
        %span.stripe.item1
        %span.stripe.item2
        %span.stripe.item3
        %span.stripe.item4
        %span.stripe.item5
        %span.stripe.item6
        %span.stripe.item7
        %span.stripe.item8
        %span.stripe.item9
        %span.stripe.item10
        %span.stripe.item11
        %span.stripe.item12
        %span.stripe.item13
        %span.stripe.item14
        %span.stripe.item15
        %span.stripe.item16
        %span.stripe.item17
        %span.stripe.item18
        %span.stripe.item19
        %span.stripe.item20
        %span.stripe.item21
        %span.stripe.item22
        %span.stripe.item23
        %span.stripe.item24
        %span.stripe.item25
        %span.stripe.item26
        %span.stripe.item27
        %span.stripe.item28
        %span.stripe.item29
        %span.stripe.item30
        %span.stripe.item31
        %span.stripe.item32
        %span.stripe.item33
        %span.stripe.item34
        %span.stripe.item35
        %span.stripe.item36
        %span.stripe.item37
        %span.stripe.item38
        %span.stripe.item39
        %span.stripe.item40
        %span.stripe.item41
        %span.stripe.item42
        %span.stripe.item43
        %span.stripe.item44
        %span.stripe.item45
        %span.stripe.item46
        %span.stripe.item47
        %span.stripe.item48
        %span.stripe.item49
        %span.stripe.item50
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
            = render 'layouts/footer'
      / ! end of .container
    / ! end of #main

app/views/programs/_form.html.haml
= simple_form_for(@program) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :autofocus => true
    = f.text_area :intro, :size => "30x5"
    %br
    = f.text_area :description, :size => "30x15"

  .form-actions
    = f.button :submit

app/views/programs/edit.html.haml
%h1 Editing program

= render 'form'

= link_to 'Show', @program
\|
= link_to 'Back', programs_path

app/views/programs/index.html.haml
%div.row
  %div.span9
    %h1 helloWorld Programs
    - @programs.each do |program|
      %div.programs
        %h2 #{link_to program.name, program}
        = program.intro
        %br
        %br
        = program.description

app/views/programs/new.html.haml
%h1 New program

= render 'form'

= link_to 'Back', programs_path

app/views/programs/show.html.haml
%p#notice= notice
%div.row
  %div.span9
    %h2 #{link_to @program.name}
    %p
      = @program.intro
    %p
      = @program.description

app/views/user_notifier/welcome_mail.html.haml
- user = @user
Hi #{user.name},

Thank you for signing up for helloWorld Tech Hub. For more information, plase call 0774942505 or 0722838469.

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}